name: pdr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cytoolz
  - numpy
  - pandas
  - git
  - dustgoggles
  - pds4_tools
  - pip
  - python-Levenshtein
  - multidict
  - more-itertools
  # optional dependencies (use minimal_environment.yml if you'd prefer not to install)
  - pvl
  - astropy
  - jupyter
  - pillow
  - matplotlib
